config/routes.rb
Rails.application.routes.draw do

 #ユーザー用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  #ゲストログイン
  devise_scope :user do
    post 'users/guest_log_in', to: 'public/sessions#guest_log_in'
  end


  scope module: :public do

    root to: 'homes#top'

    get 'about' => 'homes#about'

    get 'users' => 'users#index'
    get 'users/mypage/:id' => 'users#show', as: 'users_mypage'
    get 'users/:id/edit' => 'users#edit', as: 'edit_user'
    patch 'users/:id' => 'users#update', as: 'update_user'
    get 'users/other_user/:id' => 'users#other_user', as: 'other_user'
    resources :trip_articles do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
    end

    resources :likes, only: [:index]
    get 'search' => 'searches#search'
  end
    resources :tags do
      get 'trip_article', to: 'trip_article#search'
    end
#管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do

    get '/' => 'homes#top'

    resources :users, only: [:index, :destroy]
    resources :trip_article, only: [:destroy]
    resources :comments, only: [:index, :destroy]
    resources :tags, only: [:index, :create, :edit, :update, :destroy]

  end
end

app/models/comment.rb
class Comment < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  belongs_to :trip_article

  validates :comment, presence: true, length: { maximum: 300 }

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      # image.variant(resize_to_limit: [width, height]).processed
      image.variant(gravity: :center, resize: "#{width}x#{height}^", crop: "#{width}x#{height}+0+0")
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @trip_articles = TripArticle.all
    @comments = Comment.all
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to admin_comments_path
  end

  private

  def comment_params
    params.require(:comment)
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/index.html.erb
<h1 class= "font-weight-bold text-center p-5 mt-5">投稿・コメント管理</h1>
<div class="d-flex justify-content-center p-5 mt-3 ">
  <%=link_to 'トップ', admin_path,class: "btn  btn-outline-secondary px-5" %>
</div>

    <% @trip_articles.each do |trip_article| %>
    <div class="trip-article-card row justify-content-center pt-4">
      <div class="card d-block col-12 col-sm-6">
        <div class="card-header d-flex align-items-center">
          <div class= "rounded-circle h-100">
<% if trip_article.user.present? %>
            <%= image_tag trip_article.user&.get_image(40,40), class: "rounded-circle" %>
            <% end %>
          </div>
          <p class="m00 pl-2"><%= trip_article.user.name %></p>
        </div>
        <div class= "card-body">
            <div class="row justify-content-center p-3">
              <%= image_tag trip_article.get_image(400,500) %>
            </div>
            <div class="row justify-content-center p-2">
              <div class="card-title">
                <%= trip_article.title %>
              </div>
            </div>
              <div class="row justify-content-center pb-2">
                <%= trip_article.text %>
              </div>
              <div class="row justify-content-center pb-2">
                <%= trip_article.created_at.strftime('%Y/%m/%d') %>
                <%= link_to "投稿削除", admin_trip_article_path(trip_article.id), method: :delete, "data-confirm" => "投稿を削除しますか？", class: "btn  btn-outline-danger ml-3" %>
              </div>
              <div class="comments card-text row justify-content-center">
                <div class="row" style="width: 100%">
                  <% trip_article.comments.each do |comment| %>
                  <div class="col-12 pl-5" style="width:100%">
                    <div class="row">
                      <div class="col-12">
                        <%= image_tag comment.user.get_image(60,60), class: "rounded-circle" %>
                        <span>
                          <%= comment.comment %>
                        </span>
                      </div>
                    </div>
                    <div class="row mx-auto">
                      <div class="col-9">
                        <span class= "pr-3">
                           <%= comment.user.nickname %>
                        </span>
                        <%= comment.created_at.strftime('%Y/%m/%d') %>
                      </div>
                      <div class="col-3 pb-5">
                         <%= link_to "コメント削除", admin_comment_path(comment.id), method: :delete, "data-confirm" => "コメントを削除しますか？", class: "btn  btn-outline-danger" %>
                      </div>
                    </div>
                  </div>
                  <% end %>
                </div>
              </div>
        </div>
      </div>
    </div>
    <% end %>