config/routes.rb
Rails.application.routes.draw do

 #ユーザー用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  #ゲストログイン
  devise_scope :user do
    post 'users/guest_log_in', to: 'public/sessions#guest_log_in'
  end


  scope module: :public do

    root to: 'homes#top'

    get 'about' => 'homes#about'

    get 'users' => 'users#index'
    get 'users/mypage/:id' => 'users#show', as: 'users_mypage'
    get 'users/:id/edit' => 'users#edit', as: 'edit_user'
    patch 'users/:id' => 'users#update', as: 'update_user'
    get 'users/other_user/:id' => 'users#other_user', as: 'other_user'
    resources :trip_articles do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
    end

    resources :likes, only: [:index]
    get 'search' => 'searches#search'
  end
    resources :tags do
      get 'trip_article', to: 'trip_article#search'
    end
#管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do

    get '/' => 'homes#top'

    resources :users, only: [:index, :destroy]
    resources :trip_article, only: [:destroy]
    resources :comments, only: [:index, :destroy]
    resources :tags, only: [:index, :create, :edit, :update, :destroy]

  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<h2 class= "font-weight-bold text-center p-5 mt-5">管理者</h2>
  <div class="container justify-content-center p-5 ">
    <div class="row mx-auto">
      <div class="col-12 text-center">
         <%= link_to 'ユーザー管理', admin_users_path, class: "font-weight-bold " %>
          <div class= "col-12 p-5">
            <%= link_to '投稿＆コメント管理', admin_comments_path, class: "font-weight-bold" %>
          </div>
            <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "font-weight-bold" %>
      </div>
    </div>
  </div>