config/routes.rb
Rails.application.routes.draw do

 #ユーザー用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  #ゲストログイン
  devise_scope :user do
    post 'users/guest_log_in', to: 'public/sessions#guest_log_in'
  end


  scope module: :public do

    root to: 'homes#top'

    get 'about' => 'homes#about'

    get 'users' => 'users#index'
    get 'users/mypage/:id' => 'users#show', as: 'users_mypage'
    get 'users/:id/edit' => 'users#edit', as: 'edit_user'
    patch 'users/:id' => 'users#update', as: 'update_user'
    get 'users/other_user/:id' => 'users#other_user', as: 'other_user'
    resources :trip_articles do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
    end

    resources :likes, only: [:index]
    get 'search' => 'searches#search'
  end
    resources :tags do
      get 'trip_article', to: 'trip_article#search'
    end
#管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do

    get '/' => 'homes#top'

    resources :users, only: [:index, :destroy]
    resources :trip_article, only: [:destroy]
    resources :comments, only: [:index, :destroy]
    resources :tags, only: [:index, :create, :edit, :update, :destroy]

  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_many :trip_articles, dependent: :destroy#旅行記事
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy#お気に入り機能

  validates :nickname, presence: true, length: { minimum: 2 , maximum: 20 }, uniqueness: true
  validates :name, presence: true, length: { minimum: 2 , maximum: 20 }, uniqueness: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      # image.variant(resize_to_limit: [width, height]).processed
      image.variant(gravity: :center, resize: "#{width}x#{height}^", crop: "#{width}x#{height}+0+0")
  end

  def self.guest
    find_or_create_by!(email: 'guest@guest.mail') do |user|
      user.name = 'ゲスト'
      user.nickname = 'ゲストニックネーム'
      user.password = SecureRandom.urlsafe_base64
    end
  end
  def guest_user?
      email == 'guest@guest.mail'
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.page(params[:page])
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user)
  end


end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<h1 class="font-weight-bold text-center p-5">ユーザー一覧</h1>
<div class="row justify-content-center p-5 ">
  <%=link_to 'トップ', admin_path , class: "btn btn-outline-secondary px-5 "%>
</div>
<table class= "table table-border hover">
  <thead>
    <tr>
      <th></th>
      <th>名前</th>
      <th>ニックネーム</th>
      <th>メールアドレス</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <% @users.each do |user| %>
    <tr>
     <td><%= image_tag user.get_image(60,60), class: "rounded-circle" %></td>
     <td><%= user.name %></td>
     <td><%= user.nickname %></td>
     <td><%= user.email %></td>
     <td><%= link_to '削除', admin_user_path(user),  method: :delete, "data-confirm" => "ユーザーを削除しますか？", class: "btn btn-danger" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class= " row justify-content-center py-5">
  <%= paginate @users %>
</div>