config/routes.rb
Rails.application.routes.draw do

 #ユーザー用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  #ゲストログイン
  devise_scope :user do
    post 'users/guest_log_in', to: 'public/sessions#guest_log_in'
  end


  scope module: :public do

    root to: 'homes#top'

    get 'about' => 'homes#about'

    get 'users' => 'users#index'
    get 'users/mypage/:id' => 'users#show', as: 'users_mypage'
    get 'users/:id/edit' => 'users#edit', as: 'edit_user'
    patch 'users/:id' => 'users#update', as: 'update_user'
    get 'users/other_user/:id' => 'users#other_user', as: 'other_user'
    resources :trip_articles do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
    end

    resources :likes, only: [:index]
    get 'search' => 'searches#search'
  end
    resources :tags do
      get 'trip_article', to: 'trip_article#search'
    end
#管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do

    get '/' => 'homes#top'

    resources :users, only: [:index, :destroy]
    resources :trip_article, only: [:destroy]
    resources :comments, only: [:index, :destroy]
    resources :tags, only: [:index, :create, :edit, :update, :destroy]

  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/association_trip_article_and_tag.rb
class AssociationTripArticleAndTag < ApplicationRecord
  belongs_to :trip_article
  belongs_to :tag
end

app/models/comment.rb
class Comment < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  belongs_to :trip_article

  validates :comment, presence: true, length: { maximum: 300 }

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      # image.variant(resize_to_limit: [width, height]).processed
      image.variant(gravity: :center, resize: "#{width}x#{height}^", crop: "#{width}x#{height}+0+0")
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :trip_article #お気に入り機能

  #ユーザーが１つの投稿に対してお気に入り登録できる回数を１回
  validates :user_id, uniqueness: { scope: :trip_article_id }

end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
end

app/models/season.rb
class Season < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord

has_many :association_post_and_tags, dependent: :destroy
has_many :trip_articles, through: :association_trip_article_and_tags

validates :tag_type, presence: true
end

app/models/trip_article.rb
class TripArticle < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  belongs_to :prefecture
  belongs_to :season
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy #お気に入り機能
  # has_many :association_post_and_tags, dependent: :destroy
  # has_many :tags, through: :association_post_and_tags

  validates :title, presence: true
  validates :text, presence: true
  validates :image, attached: true, content_type: ["image/jpg", "image/jpeg"]

  def liked_by(user)
    Like.find_by(user_id: user.id, trip_article_id: id)
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_many :trip_articles, dependent: :destroy#旅行記事
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy#お気に入り機能

  validates :nickname, presence: true, length: { minimum: 2 , maximum: 20 }, uniqueness: true
  validates :name, presence: true, length: { minimum: 2 , maximum: 20 }, uniqueness: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      # image.variant(resize_to_limit: [width, height]).processed
      image.variant(gravity: :center, resize: "#{width}x#{height}^", crop: "#{width}x#{height}+0+0")
  end

  def self.guest
    find_or_create_by!(email: 'guest@guest.mail') do |user|
      user.name = 'ゲスト'
      user.nickname = 'ゲストニックネーム'
      user.password = SecureRandom.urlsafe_base64
    end
  end
  def guest_user?
      email == 'guest@guest.mail'
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @trip_articles = TripArticle.all
    @comments = Comment.all
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to admin_comments_path
  end

  private

  def comment_params
    params.require(:comment)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.page(params[:page])
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    trip_articles_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

   protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nickname, :email])
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/trip_article_helper.rb
module Admin::TripArticleHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tabimaru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <%= favicon_link_tag('favicon.ico') %>
    <script src="https://kit.fontawesome.com/d85941bf84.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css"/>
    <script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <header>
      <div id="hamburger">
        <ul>
          <% if user_signed_in? %>
            <li><%= link_to 'トップ', root_path %></li>
            <li><%= link_to 'マイページ', users_mypage_path(current_user.id) %></li>
            <li><%= link_to 'ユーザー', users_path %></li>
            <li><%= link_to 'お気に入り',  likes_path(id: current_user.id) %></li>
            <li><%= link_to '投稿一覧', trip_articles_path %></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          <% elsif admin_signed_in? %>
            <li><%= link_to 'トップ', admin_path %></li>
            <li><%= link_to 'ユーザー一覧', admin_users_path %></li>
            <li><%= link_to '投稿・コメント管理', admin_comments_path %></li>
            <li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'トップ', root_path %></li>
            <li><%= link_to 'Tabimaruについて', about_path %></li>
            <li><%= link_to '新規登録', new_user_registration_path %></li>
            <li><%= link_to 'ログイン', new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
      <div id="hm-icon">
      <a class="menu-trigger" href="#">
        <span></span>
        <span></span>
        <span></span>
      </a>
    </div>
    </header>
    <%= yield %>
    <footer class="fixed-bottom text-center mx-0 bg-dark bg-opacity-75 text-white" >©️2023 KURO</footer>
  </body>
</html>